version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.google.guava:guava"
      - dependency-name: "com.google.guava:guava-testlib"
      - dependency-name: "com.google.guava:guava-gwt"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
